// ============================================================
// BuildCart MVP — Sample Data (Kenyan construction marketplace)
// ============================================================

const CATEGORIES = [
  { id: 'cement', name: 'Cement', icon: 'fa-cubes', description: 'All grades from trusted brands' },
  { id: 'steel', name: 'Steel & Binding Wire', icon: 'fa-bars', description: 'Reinforcement bars & wire' },
  { id: 'roofing', name: 'Roofing Sheets', icon: 'fa-home', description: 'Corrugated & box profile' },
  { id: 'plumbing', name: 'Plumbing', icon: 'fa-faucet', description: 'PVC pipes, fittings & valves' },
  { id: 'electrical', name: 'Electrical', icon: 'fa-bolt', description: 'Cables, conduit & wiring' },
  { id: 'finishes', name: 'Finishes', icon: 'fa-paint-roller', description: 'Paint, tiles & decor' },
  { id: 'timber', name: 'Timber', icon: 'fa-tree', description: 'Hardwood & softwood' },
  { id: 'blocks', name: 'Blocks & Bricks', icon: 'fa-building', description: 'Concrete blocks & clay bricks' },
  { id: 'aggregate', name: 'Aggregate & Sand', icon: 'fa-mountain', description: 'Ballast, sand & murram' },
];

const BRANDS = {
  cement: ['Bamburi', 'Mombasa Cement', 'Rhino', 'Savanna', 'Dangote'],
  steel: ['Apex Africa', 'Royal Mabati', 'Devki Steel', 'Insteel'],
  roofing: ['Mabati Rolling Mills', 'Royal Mabati', 'Super Mabati', 'Namisha'],
  plumbing: ['Durapipe', 'PVC Kenya', 'Georg Fischer', 'Tigre'],
  electrical: ['Cable Manufacturers Kenya', 'Ridgeback', 'CentraLab', 'ABB'],
  finishes: ['Crown Paints', 'Sadolin', 'Dulux', 'Armstrong', 'Bamburi Flooring'],
  timber: ['Pan African', 'Timken', 'Raemoir', 'Local Sawmills'],
  blocks: ['Bamburi', 'Local Suppliers', 'Hydraform'],
  aggregate: ['Local Quarries', 'Bamburi', 'Various Suppliers'],
};

const PRODUCTS = [
  // ===== CEMENT =====
  { id: 'cem-001', name: 'Bamburi Portland Cement 42.5N', category: 'cement', brand: 'Bamburi', price: 720, unit: 'per 50kg bag', image: 'https://images.unsplash.com/photo-1587394144759-5a0e1b8b9d8c?w=400&h=400&fit=crop', inStock: true, description: 'Bamburi Portland Cement 42.5N is the most popular general-purpose cement in Kenya. Ideal for structural concrete, foundations, columns, beams, and slabs. Meets KS EAS 18-1:2017 standard.', features: ['42.5N strength class', 'eTIMS compliant', 'Ideal for structural work', '50kg bag'] },
  { id: 'cem-002', name: 'Mombasa Cement Nyumba 42.5N', category: 'cement', brand: 'Mombasa Cement', price: 650, unit: 'per 50kg bag', image: 'https://images.unsplash.com/photo-1593410131745-6e78a60ab6c6?w=400&h=400&fit=crop', inStock: true, description: 'Mombasa Cement Nyumba brand offers reliable performance at competitive pricing. Suitable for general construction, plastering, and masonry work.', features: ['42.5N strength class', 'eTIMS compliant', 'Great value', '50kg bag'] },
  { id: 'cem-003', name: 'Rhino Cement 32.5R', category: 'cement', brand: 'Rhino', price: 580, unit: 'per 50kg bag', image: 'https://images.unsplash.com/photo-1581094794329-0e8499f5e7d8?w=400&h=400&fit=crop', inStock: true, description: 'Rhino Cement 32.5R is a rapid-hardening cement ideal for plastering, screeding, and non-structural applications. Sets faster for quicker project turnaround.', features: ['32.5R rapid hardening', 'eTIMS compliant', 'Best for plaster', '50kg bag'] },
  { id: 'cem-004', name: 'Savanna Cement 42.5N', category: 'cement', brand: 'Savanna', price: 630, unit: 'per 50kg bag', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Savanna Cement provides consistent quality for all-round construction needs. Locally manufactured with strict quality controls.', features: ['42.5N strength class', 'Consistent quality', 'eTIMS compliant', '50kg bag'] },
  { id: 'cem-005', name: 'Dangote Cement 42.5R', category: 'cement', brand: 'Dangote', price: 670, unit: 'per 50kg bag', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: 'Dangote 42.5R offers rapid early strength gain, perfect for projects needing fast formwork removal and quick progress.', features: ['42.5R rapid strength', 'Early strength gain', 'eTIMS compliant', '50kg bag'] },

  // ===== STEEL =====
  { id: 'stl-001', name: 'Y12 Reinforcement Bar (12mm)', category: 'steel', brand: 'Devki Steel', price: 900, unit: 'per 12m bar', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: 'High-yield 12mm deformed reinforcement bar. Grade 500D, perfect for columns, beams, and slabs. Cut and bent to order.', features: ['Grade 500D', '12m standard length', 'KS 263 compliant', 'Deformed pattern'] },
  { id: 'stl-002', name: 'Y10 Reinforcement Bar (10mm)', category: 'steel', brand: 'Devki Steel', price: 650, unit: 'per 12m bar', image: 'https://images.unsplash.com/photo-1513836279014-7a0aae8b3b7e?w=400&h=400&fit=crop', inStock: true, description: 'High-yield 10mm deformed bar for lighter reinforcement needs — stirrups, ties, and slab mesh.', features: ['Grade 500D', '12m standard length', 'KS 263 compliant', 'Ideal for stirrups'] },
  { id: 'stl-003', name: 'Y16 Reinforcement Bar (16mm)', category: 'steel', brand: 'Apex Africa', price: 1600, unit: 'per 12m bar', image: 'https://images.unsplash.com/photo-1565108578519-0e8f5c1d2e3f?w=400&h=400&fit=crop', inStock: true, description: '16mm high-yield deformed bar for heavy structural reinforcement. Columns, beams, and foundation footings.', features: ['Grade 500D', '12m standard length', 'Heavy structural', 'KS 263 compliant'] },
  { id: 'stl-004', name: 'Y8 Reinforcement Bar (8mm)', category: 'steel', brand: 'Insteel', price: 420, unit: 'per 12m bar', image: 'https://images.unsplash.com/photo-1504328345492-6c8b1d1b7e1f?w=400&h=400&fit=crop', inStock: true, description: '8mm mild steel bar ideal for stirrups, links, and light mesh reinforcement.', features: ['Grade 500D', '12m standard length', 'Light reinforcement', 'KS 263 compliant'] },
  { id: 'stl-005', name: 'Binding Wire 1.6mm (20kg Roll)', category: 'steel', brand: 'Devki Steel', price: 2800, unit: 'per 20kg roll', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Black annealed binding wire for tying reinforcement bars. 1.6mm gauge, 20kg roll. Soft and easy to twist.', features: ['1.6mm gauge', 'Black annealed', '20kg roll', 'Easy twist tie'] },

  // ===== ROOFING =====
  { id: 'rof-001', name: 'Corrugated Iron Sheet 30G (3m)', category: 'roofing', brand: 'Mabati Rolling Mills', price: 850, unit: 'per sheet', image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=400&h=400&fit=crop', inStock: true, description: 'Classic corrugated galvanized iron roofing sheet, 30-gauge thickness, 3-metre length. Durable, weather-resistant, Kenya's most popular roofing profile.', features: ['30 gauge', 'Galvanized', '3m length', 'Classic corrugated profile'] },
  { id: 'rof-002', name: 'Box Profile Sheet 30G (3m)', category: 'roofing', brand: 'Royal Mabati', price: 1050, unit: 'per sheet', image: 'https://images.unsplash.com/photo-1564013799919-6e2f1c6e1b3c?w=400&h=400&fit=crop', inStock: true, description: 'Modern box profile roofing sheet with a sleek, contemporary look. 30-gauge, 3-metre length. Interlocking design for better weather sealing.', features: ['30 gauge', 'Box profile design', 'Interlocking', '3m length'] },
  { id: 'rof-003', name: 'Clay Tile Profile Mabati 30G (2.4m)', category: 'roofing', brand: 'Super Mabati', price: 1200, unit: 'per sheet', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Clay tile profile mabati offers the classic tile look with modern steel durability. Great for residential homes wanting an elegant roofline.', features: ['30 gauge', 'Tile profile aesthetic', 'Steel durability', '2.4m length'] },
  { id: 'rof-004', name: 'Corrugated Iron Sheet 28G (3m)', category: 'roofing', brand: 'Mabati Rolling Mills', price: 1200, unit: 'per sheet', image: 'https://images.unsplash.com/photo-1593410131745-6e78a60ab6c6?w=400&h=400&fit=crop', inStock: true, description: 'Heavy-duty 28-gauge corrugated sheet for premium durability. Thicker gauge means longer life — ideal for areas with harsh weather.', features: ['28 gauge — heavy duty', 'Galvanized', '3m length', 'Longer lifespan'] },
  { id: 'rof-005', name: 'Ridge Cap 30G (2.4m)', category: 'roofing', brand: 'Namisha', price: 550, unit: 'per piece', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: 'Galvanized ridge cap for finishing roof ridges. 30-gauge, 2.4-metre length. Matches standard corrugated and box profiles.', features: ['30 gauge', '2.4m length', 'Galvanized finish', 'Universal fit'] },

  // ===== PLUMBING =====
  { id: 'plb-001', name: 'PVC Pipe 4-inch (3m)', category: 'plumbing', brand: 'Durapipe', price: 850, unit: 'per pipe', image: 'https://images.unsplash.com/photo-1585704034275-41a8b5e3c0f1?w=400&h=400&fit=crop', inStock: true, description: '4-inch (100mm) PVC soil pipe for sewerage and drainage systems. 3-metre length. Heavy-duty, compliant with KS 263.', features: ['4-inch / 100mm diameter', '3m length', 'Heavy duty', 'KS 263 compliant'] },
  { id: 'plb-002', name: 'PVC Pipe 1/2-inch (3m)', category: 'plumbing', brand: 'Tigre', price: 280, unit: 'per pipe', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: '1/2-inch PVC pressure pipe for cold water supply. 3-metre length. Class D rated for standard residential pressure.', features: ['1/2-inch diameter', '3m length', 'Class D rated', 'Cold water supply'] },
  { id: 'plb-003', name: 'PVC Elbow 90° (1/2-inch)', category: 'plumbing', brand: 'Durapipe', price: 45, unit: 'per piece', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: '90-degree elbow fitting for 1/2-inch PVC pipes. Solvent-weld joint for leak-free plumbing.', features: ['90° angle', '1/2-inch fitting', 'Solvent weld', 'Leak-free'] },
  { id: 'plb-004', name: 'Gate Valve 1-inch', category: 'plumbing', brand: 'Georg Fischer', price: 750, unit: 'per piece', image: 'https://images.unsplash.com/photo-1504328345492-6c8b1d1b7e1f?w=400&h=400&fit=crop', inStock: true, description: 'Brass gate valve for 1-inch water supply lines. Full-bore design for unrestricted flow. Ideal for main shut-off.', features: ['Brass body', '1-inch bore', 'Full flow', 'Main shut-off'] },
  { id: 'plb-005', name: 'PVC Tee Fitting (4-inch)', category: 'plumbing', brand: 'Durapipe', price: 180, unit: 'per piece', image: 'https://images.unsplash.com/photo-1587394144759-5a0e1b8b9d8c?w=400&h=400&fit=crop', inStock: true, description: '4-inch PVC tee fitting for branching sewer lines. Solvent-weld connection for reliable drainage.', features: ['4-inch diameter', 'Tee configuration', 'Solvent weld', 'Sewer grade'] },

  // ===== ELECTRICAL =====
  { id: 'ele-001', name: '2.5mm² Single Core Cable (100m)', category: 'electrical', brand: 'Cable Manufacturers Kenya', price: 4500, unit: 'per 100m roll', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: '2.5mm² single core copper cable for ring circuits and power outlets. 100-metre roll. Stranded copper conductor with PVC insulation.', features: ['2.5mm² cross-section', '100m roll', 'Copper conductor', 'PVC insulated'] },
  { id: 'ele-002', name: '1.5mm² Single Core Cable (100m)', category: 'electrical', brand: 'Cable Manufacturers Kenya', price: 3200, unit: 'per 100m roll', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: '1.5mm² single core copper cable for lighting circuits. 100-metre roll. KS 263 compliant.', features: ['1.5mm² cross-section', '100m roll', 'Lighting circuits', 'KS 263 compliant'] },
  { id: 'ele-003', name: '20mm PVC Conduit (3m)', category: 'electrical', brand: 'CentraLab', price: 150, unit: 'per pipe', image: 'https://images.unsplash.com/photo-1593410131745-6e78a60ab6c6?w=400&h=400&fit=crop', inStock: true, description: '20mm PVC electrical conduit for surface or concealed wiring. 3-metre length. Medium duty.', features: ['20mm diameter', '3m length', 'Medium duty', 'Surface or concealed'] },
  { id: 'ele-004', name: '32A DP Switch Socket', category: 'electrical', brand: 'ABB', price: 380, unit: 'per piece', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: '32A double-pole switched socket outlet. White finish. For heavy appliances — cookers, showers, etc.', features: ['32A rated', 'Double pole', 'White finish', 'Heavy appliance'] },
  { id: 'ele-005', name: '6mm² Earth Cable (100m)', category: 'electrical', brand: 'Ridgeback', price: 5800, unit: 'per 100m roll', image: 'https://images.unsplash.com/photo-1585704034275-41a8b5e3c0f1?w=400&h=400&fit=crop', inStock: true, description: '6mm² green/yellow earth continuity conductor. 100-metre roll. Essential for safe earthing of installations.', features: ['6mm² cross-section', 'Green/yellow insulation', '100m roll', 'Earth continuity'] },

  // ===== FINISHES =====
  { id: 'fin-001', name: 'Crown Weathercoat Guard Exterior Paint (20L)', category: 'finishes', brand: 'Crown Paints', price: 8500, unit: 'per 20L', image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&h=400&fit=crop', inStock: true, description: 'Crown Weathercoat Guard is a premium exterior paint with UV protection and weather resistance. Covers up to 120m² per 20L.', features: ['UV protection', 'Weather resistant', '20L bucket', '~120m² coverage'] },
  { id: 'fin-002', name: 'Sadolin Super Decor Interior (20L)', category: 'finishes', brand: 'Sadolin', price: 7200, unit: 'per 20L', image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3a3506?w=400&h=400&fit=crop', inStock: true, description: 'Sadolin Super Decor vinyl silk emulsion for interior walls. Washable, low-odour, quick-drying. Wide colour range available.', features: ['Vinyl silk finish', 'Washable', 'Low odour', '20L bucket'] },
  { id: 'fin-003', name: 'Ceramic Floor Tile 30x60cm (per m²)', category: 'finishes', brand: 'Bamburi Flooring', price: 1800, unit: 'per m²', image: 'https://images.unsplash.com/photo-1502005229762-cf1b2d7fe8f1?w=400&h=400&fit=crop', inStock: true, description: 'Premium ceramic floor tiles, 30x60cm format. Durable glazed surface, easy to clean. Multiple colours and patterns in stock.', features: ['30x60cm format', 'Glazed surface', 'High durability', 'Multiple colours'] },
  { id: 'fin-004', name: 'Dulux Weathershield Exterior (10L)', category: 'finishes', brand: 'Dulux', price: 5200, unit: 'per 10L', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Dulux Weathershield provides 8-year weather protection for exterior masonry. Smooth finish, anti-fade technology.', features: ['8-year protection', 'Anti-fade', 'Smooth finish', '10L can'] },
  { id: 'fin-005', name: 'Wall Primer Undercoat (20L)', category: 'finishes', brand: 'Crown Paints', price: 4800, unit: 'per 20L', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: 'Quality alkali-resisting primer for new plaster and masonry. Essential first coat for long-lasting paint finishes.', features: ['Alkali resisting', 'New plaster suitable', '20L bucket', 'Essential undercoat'] },

  // ===== TIMBER =====
  { id: 'tim-001', name: 'Cypress Timber 2x6 (3.6m)', category: 'timber', brand: 'Local Sawmills', price: 650, unit: 'per piece', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Treated cypress timber, 2×6 inch profile, 3.6-metre length. Ideal for rafters, frames, and general carpentry.', features: ['2×6 inch profile', '3.6m length', 'Treated', 'Cypress species'] },
  { id: 'tim-002', name: 'Eucalyptus Pole 4-inch (3m)', category: 'timber', brand: 'Local Sawmills', price: 450, unit: 'per piece', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: 'Treated eucalyptus pole for fencing, scaffolding, and support structures. 4-inch diameter, 3-metre length.', features: ['4-inch diameter', '3m length', 'Treated', 'Scaffolding grade'] },
  { id: 'tim-003', name: 'Hardwood Door Frame Set', category: 'timber', brand: 'Pan African', price: 4500, unit: 'per set', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Pre-made hardwood door frame for standard 900mm door openings. Includes head and two jambs.', features: ['Hardwood species', '900mm opening', 'Complete frame', 'Pre-assembled'] },
  { id: 'tim-004', name: 'MDF Board 8x4ft (18mm)', category: 'timber', brand: 'Pan African', price: 2800, unit: 'per board', image: 'https://images.unsplash.com/photo-1593410131745-6e78a60ab6c6?w=400&h=400&fit=crop', inStock: true, description: 'Medium Density Fibreboard, 18mm thick, 8×4 foot sheet. Ideal for built-in cabinets, shelving, and interior paneling.', features: ['18mm thickness', '8×4ft sheet', 'Smooth surface', 'Interior use'] },

  // ===== BLOCKS & BRICKS =====
  { id: 'blk-001', name: 'Concrete Block 6-inch', category: 'blocks', brand: 'Local Suppliers', price: 55, unit: 'per block', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: 'Standard 6-inch concrete block for wall construction. Compressive strength 3.5MPa. Made to KS 263 standard.', features: ['6-inch / 150mm', '3.5MPa strength', 'KS 263 standard', 'Cured & ready'] },
  { id: 'blk-002', name: 'Concrete Block 8-inch', category: 'blocks', brand: 'Local Suppliers', price: 70, unit: 'per block', image: 'https://images.unsplash.com/photo-1581094794329-0e8499f5e7d8?w=400&h=400&fit=crop', inStock: true, description: '8-inch concrete block for load-bearing and party walls. Higher compressive strength for structural applications.', features: ['8-inch / 200mm', 'Structural grade', 'KS 263 standard', 'Load bearing'] },
  { id: 'blk-003', name: 'Clay Brick (Stock)', category: 'blocks', brand: 'Hydraform', price: 25, unit: 'per brick', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Fired clay stock brick for facing walls and decorative features. Red/terracotta colour. 215×102.5×65mm.', features: ['Fired clay', '215×102.5×65mm', 'Red/terracotta', 'Facing grade'] },
  { id: 'blk-004', name: 'Interlocking Stabilised Soil Block (ISSB)', category: 'blocks', brand: 'Hydraform', price: 35, unit: 'per block', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: 'Hydraform ISSB interlocking block — no mortar needed for wall construction. Earth-friendly, cost-effective, fast to lay.', features: ['Interlocking design', 'No mortar needed', 'Eco-friendly', 'Fast construction'] },

  // ===== AGGREGATE & SAND =====
  { id: 'agg-001', name: 'Ballast (3/4 inch) — per tonne', category: 'aggregate', brand: 'Local Quarries', price: 4500, unit: 'per tonne', image: 'https://images.unsplash.com/photo-1504917595217-d6dc5b3a3b3d?w=400&h=400&fit=crop', inStock: true, description: '3/4-inch crushed stone ballast for concrete mixing and foundation work. Delivered in Nairobi Metro within 1–3 days.', features: ['3/4 inch graded', 'Crushed stone', 'Concrete grade', 'Per tonne'] },
  { id: 'agg-002', name: 'Building Sand — per tonne', category: 'aggregate', brand: 'Local Quarries', price: 3500, unit: 'per tonne', image: 'https://images.unsplash.com/photo-1504307651259-4d2bc4deba23?w=400&h=400&fit=crop', inStock: true, description: 'Clean river sand for mortar, plaster, and concrete mixes. Screened and washed. Nairobi Metro delivery.', features: ['River sand', 'Screened & washed', 'Multi-use', 'Per tonne'] },
  { id: 'agg-003', name: 'Murram / Red Soil — per tonne', category: 'aggregate', brand: 'Local Quarries', price: 2800, unit: 'per tonne', image: 'https://images.unsplash.com/photo-1593410131745-6e78a60ab6c6?w=400&h=400&fit=crop', inStock: true, description: 'Compacted murram / red soil for site grading, road base, and filling. Nairobi Metro delivery available.', features: ['Red soil / murram', 'For grading & fill', 'Compaction grade', 'Per tonne'] },
  { id: 'agg-004', name: 'Quarry Dust — per tonne', category: 'aggregate', brand: 'Local Quarries', price: 3000, unit: 'per tonne', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop', inStock: true, description: 'Fine quarry dust for blinding, slab bases, and as a sand substitute in mortar. Cost-effective fill material.', features: ['Fine grade', 'Blinding / slab base', 'Sand substitute', 'Per tonne'] },
];

// ===== FUNDI / SERVICE PROFILES =====
const SERVICE_CATEGORIES = [
  { id: 'plumbing', name: 'Plumbing', icon: 'fa-faucet', description: 'Pipe installation, repairs, water systems' },
  { id: 'tiling', name: 'Tiling', icon: 'fa-border-all', description: 'Floor & wall tiling, grouting' },
  { id: 'electrical', name: 'Electrical', icon: 'fa-bolt', description: 'Wiring, installations, safety checks' },
  { id: 'painting', name: 'Painting', icon: 'fa-paint-roller', description: 'Interior & exterior painting' },
  { id: 'roofing', name: 'Roofing Installation', icon: 'fa-home', description: 'Roof fitting, repairs, gutters' },
  { id: 'handyman', name: 'General Handyman', icon: 'fa-tools', description: 'Fixes, assembly, minor works' },
];

const FUNDIS = [
  { id: 'fun-001', name: 'Joseph Mwangi', trade: 'plumbing', category: 'Plumber', rating: 4.8, jobs: 127, location: 'Nairobi — Westlands', experience: '12 years', licensed: true, bio: 'Certified plumber with 12 years in residential and commercial plumbing. Specializes in water systems, drainage, and bathroom installations. Trained at Kenya Water Institute.', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f3d?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-002', name: 'Peter Otieno', trade: 'tiling', category: 'Tiler', rating: 4.9, jobs: 98, location: 'Nairobi — Karen', experience: '8 years', licensed: true, bio: 'Expert tiler specializing in ceramic, porcelain, and natural stone. Clean lines, perfect grouting, fast completion. Worked on over 90 residential projects.', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-003', name: 'David Kamau', trade: 'electrical', category: 'Electrician', rating: 4.7, jobs: 215, location: 'Nairobi — Kilimani', experience: '15 years', licensed: true, bio: 'Licensed electrician Grade A1. 15 years experience in residential and light commercial wiring. EPRA certified. Focus on safety and neat installations.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-004', name: 'Samuel Wanjiku', trade: 'painting', category: 'Painter', rating: 4.6, jobs: 64, location: 'Nairobi — Rongai', experience: '6 years', licensed: true, bio: 'Interior and exterior painting specialist. Expert in colour matching, textured finishes, and weatherproof coatings. Neat, efficient, and reliable.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-005', name: 'James Kariuki', trade: 'roofing', category: 'Roofer', rating: 4.8, jobs: 89, location: 'Nairobi — Langata', experience: '10 years', licensed: true, bio: 'Roofing specialist — mabati, tile profile, and box profile installations. Guttering, flashing, and roof repairs. Fully insured.', avatar: 'https://images.unsplash.com/photo-1504257432360-9b5e5b0a4b8c?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-006', name: 'Francis Njoroge', trade: 'handyman', category: 'General Handyman', rating: 4.5, jobs: 43, location: 'Nairobi — Kasarani', experience: '5 years', licensed: false, bio: 'Reliable handyman for minor repairs, furniture assembly, gate installation, and general fix-it tasks. Punctual and clean.', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7400c?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-007', name: 'Mary Akinyi', trade: 'plumbing', category: 'Plumber', rating: 4.9, jobs: 78, location: 'Nairobi — Eastlands', experience: '9 years', licensed: true, bio: 'One of Nairobi's top-rated female plumbers. Specializes in bathroom remodels, water heater installation, and pipe replacement. NCA registered.', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face', verified: true },
  { id: 'fun-008', name: 'Alex Mutua', trade: 'electrical', category: 'Electrician', rating: 4.6, jobs: 56, location: 'Nairobi — Thika Road', experience: '7 years', licensed: true, bio: 'Electrical installation and repair specialist. Solar wiring, generator connections, and smart home setups. EPRA certified.', avatar: 'https://images.unsplash.com/photo-1539571696357-5a6975100a10?w=200&h=200&fit=crop&crop=face', verified: true },
];

// Make data globally available
window.BUILDCART_DATA = { CATEGORIES, BRANDS, PRODUCTS, SERVICE_CATEGORIES, FUNDIS };
